#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
// #include "includes/stub/stub.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

// void basic_test(bool debug=false);

int main()
{
    // TODO: initialize variable

    char ans;
    do {
        // TODO: add code
        
    } while (ans == 'y');

    return 0;
}


// void basic_test(bool debug)
// {
//     if (stub()) {
//         cout << "Passed!" << endl;
//     } else {
//         cout << "Failed!" << endl;
//     }
// }


/*
folder structure:
02_04_pay_increase
├── includes
│   └── stub
│       ├── stub.cpp
│       └── stub.h
├── main.cpp
└── submit.sh

Output:

   Annual salary: 100000
      Old salary: 100000.00
        Increase: 12.00%
      new salary: 112000.00
monthly increase: 1000.00
           retro: 6000.00
again? n
*/
