#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
// #include "includes/stub/stub.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

// void basic_test(bool debug=false);

int main()
{
    // TODO
    // initialize variable

    char ans;
    do {
        // code
        
    } while (ans == 'y');

    return 0;
}


// void basic_test(bool debug)
// {
//     if (stub()) {
//         cout << "Passed!" << endl;
//     } else {
//         cout << "Failed!" << endl;
//     }
// }


/*
folder structure:
02_03_cereal_box
├── includes
│   └── stub
│       ├── stub.cpp
│       └── stub.h
├── main.cpp
└── submit.sh

Output:

cereal box in oz: 1
a 1.00 oz box of cereal is 0.0000283 tons
it takes 35273.92 boxes to make up one metric ton
again? y
cereal box in oz: 99.12
a 99.12 oz box of cereal is 0.0028100 tons
it takes 355.87 boxes to make up one metric ton
again? n
*/
