#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
// #include "includes/stub/stub.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

void basic_test(bool debug=false);

int main()
{
    int ex;
    char ans;
    do {
        cout << "Which exercise? ";
        cin >> ex;
        if (ex == 1) {
            // TODO: Exercise 1
        } else if (ex == 2) {
            // TODO: Exercise 2
        } else if (ex == 3) {
            // TODO: Exercise 3
        } else {
            cout << "There is no exercise: #" << ex << endl;
        }
        cout << "again? ";
        cin >> ans;
    } while (ans == 'y');
    return 0;
}


// void basic_test(bool debug)
// {
//     if (stub()) {
//         cout << "Passed!" << endl;
//     } else {
//         cout << "Failed!" << endl;
//     }
// }


/*
folder structure:
01_01_math_variables
├── includes
│   └── stub
│       ├── stub.cpp
│       └── stub.h
├── main.cpp
└── submit.sh

Output:

Which exercise? 1
Enter the first integer: 10
Enter the second integer: 25
10 + 25 = 35
10 * 25 = 250
10 / 25 = 0
10 % 25 = 10


Which exercise? 2
Enter six fp numbers on a single line, separated by spaces: 1.5 2.1 3.8 4.2 5.7 6.1
Sum of 1.5 + 2.1 + 3.8 + 4.2 + 5.7 + 6.1 = 23.4
Average = 3.9


Which exercise? 3
What is your age? 25
Your target heart rate is between 117 and 146.25 bpm.
*/
