#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
// #include "includes/stub/stub.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

// void basic_test(bool debug=false);

int main()
{
    // TODO: initialize variable

    char ans;
    do {
        // TODO: add code

        cout << "again? ";
        cin >> ans;
    } while (ans == 'y');

    return 0;
}


// void basic_test(bool debug)
// {
//     if (stub()) {
//         cout << "Passed!" << endl;
//     } else {
//         cout << "Failed!" << endl;
//     }
// }


/*
folder structure:
02_06_cash_register
├── includes
│   └── stub
│       ├── stub.cpp
│       └── stub.h
├── main.cpp
└── submit.sh

Output:

Enter purchase amount: 18.89
Enter amount received: 20
Total Change: $1.11

dollars 1
quarters 0
dimes 1
nickels 0
pennies 1
again? y
Enter purchase amount: 25.56
Enter amount received: 40
Total Change: $14.44

dollars 14
quarters 1
dimes 1
nickels 1
pennies 4
again? n
*/
