#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
// #include "includes/stub/stub.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

void basic_test(bool debug=false);

int main()
{
  // TODO

  // initialize string variable

  // ask user to input

  // output "Hi, there ... !"

  
  return 0;
}


// void basic_test(bool debug)
// {
//   if (stub()) {
//     cout << "Passed!" << endl;
//   } else {
//     cout << "Failed!" << endl;
//   }
// }

/*
folder structure:
00_lab_0
├── includes
│   └── stub
│       ├── stub.cpp
│       └── stub.h
├── main.cpp
└── submit.sh

Output:

CS
Hi, there CS !
world
Hi, there world !
Prof
Hi, there Prof !
*/
