#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
// #include "includes/stub/stub.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

void basic_test(bool debug=false);

int main()
{
    int ex;
    char ans;
    do {
        cout << "Which exercise? ";
        cin >> ex;
        if (ex == 1) {
            // TODO: Exercise 1
        } else if (ex == 2) {
            // TODO: Exercise 2
        } else {
            cout << "There is no exercise: #" << ex << endl;
        }
        cout << "again? ";
        cin >> ans;
    } while (ans == 'y');
    return 0;
}


// void basic_test(bool debug)
// {
//     if (stub()) {
//         cout << "Passed!" << endl;
//     } else {
//         cout << "Failed!" << endl;
//     }
// }


/*
folder structure:
02_02_arithmetic_operations
├── includes
│   └── stub
│       ├── stub.cpp
│       └── stub.h
├── main.cpp
└── submit.sh

Output:

Which exercise? 1
Exercise 1:
Please enter the first 9 digits of the ISBN: 123456789

Checksum: 10
again?
y

Which exercise? 2
Exercise 2:
Enter a character: b

b is letter 2
again?
n
*/
